#!/bin/sh
set -e
cat > /usr/share/nginx/html/env.js << EOF
window._ENV_ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL}",
  VITE_OIDC_AUTHORITY: "${VITE_OIDC_AUTHORITY}",
  VITE_OIDC_CLIENT_ID: "${VITE_OIDC_CLIENT_ID}",
  VITE_OIDC_REDIRECT_URI: "${VITE_OIDC_REDIRECT_URI}",
  VITE_OIDC_POST_LOGOUT_REDIRECT_URI: "${VITE_OIDC_POST_LOGOUT_REDIRECT_URI}",
  VITE_OIDC_AUDIENCE: "${VITE_OIDC_AUDIENCE}"
};
EOF
exec nginx -g 'daemon off;'
