apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: discord
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          use_discord_username: true
          title: '{{ template "kontor.title" . }}'
          message: '{{ template "kontor.message" . }}'
