{{- if and (not .Values.core.existingMarketDataSecret) .Values.core.twelveDataApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kontor.core.marketDataSecretName" . }}
  labels:
    {{- include "kontor.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
type: Opaque
stringData:
  TWELVE_DATA_API_KEY: {{ .Values.core.twelveDataApiKey | quote }}
{{- end }}
