{{- if and .Values.keycloak.deploy (eq .Values.keycloak.database "postgres") }}
{{ include "kontor.postgres.statefulset" (dict "root" . "fullname" (include "kontor.keycloak.postgres.fullname" .) "component" "keycloak-db" "secretName" (include "kontor.keycloak.postgres.secretName" .) "db" .Values.keycloak.db "scheduling" .Values.keycloak) }}
{{- end }}
