{{- if .Values.postgres.enabled }}
{{ include "kontor.postgres.statefulset" (dict "root" . "fullname" (include "kontor.postgres.fullname" .) "component" "postgres" "secretName" (include "kontor.postgres.secretName" .) "db" .Values.postgres "scheduling" .Values.postgres) }}
{{- end }}
