// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: aec3a023f1b135bc224a09b6b23438d8d47ddffef174e9ae851468d1fbee712e


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "kontor";

export const themeNames: ThemeName[] = ["kontor"];

export type KcEnvName = "SHADCN_THEME_LOGO_WHITE_URL" | "SHADCN_THEME_LOGO_DARK_URL" | "SHADCN_THEME_APP_NAME" | "SHADCN_THEME_LAYOUT" | "SHADCN_THEME_SIDE_IMAGE_URL" | "SHADCN_THEME_PRESET" | "SHADCN_THEME_BASE" | "SHADCN_THEME_RADIUS" | "SHADCN_THEME_FONT" | "SHADCN_THEME_PLACEHOLDER";

export const kcEnvNames: KcEnvName[] = ["SHADCN_THEME_LOGO_WHITE_URL", "SHADCN_THEME_LOGO_DARK_URL", "SHADCN_THEME_APP_NAME", "SHADCN_THEME_LAYOUT", "SHADCN_THEME_SIDE_IMAGE_URL", "SHADCN_THEME_PRESET", "SHADCN_THEME_BASE", "SHADCN_THEME_RADIUS", "SHADCN_THEME_FONT", "SHADCN_THEME_PLACEHOLDER"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "SHADCN_THEME_LOGO_WHITE_URL": "%BASE_URL%/kontor.png",
  "SHADCN_THEME_LOGO_DARK_URL": "%BASE_URL%/kontor.png",
  "SHADCN_THEME_APP_NAME": "Kontor",
  "SHADCN_THEME_LAYOUT": "two-column",
  "SHADCN_THEME_SIDE_IMAGE_URL": "",
  "SHADCN_THEME_PRESET": "neutral",
  "SHADCN_THEME_BASE": "zinc",
  "SHADCN_THEME_RADIUS": "medium",
  "SHADCN_THEME_FONT": "roboto",
  "SHADCN_THEME_PLACEHOLDER": "true"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
