apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kontor-ci
  namespace: team-3m
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kontor-ci-app
subjects:
  - kind: ServiceAccount
    name: kontor-ci
    namespace: team-3m
