apiVersion: v1
kind: ServiceAccount
metadata:
  name: kontor-ci
  namespace: team-3m
---
apiVersion: v1
kind: Secret
metadata:
  name: kontor-ci-token
  namespace: team-3m
  annotations:
    kubernetes.io/service-account.name: kontor-ci
type: kubernetes.io/service-account-token
