import json
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, ValidationError

from .config import Settings, get_settings
from .logos import LOGOS_MODEL, make_logos_client

DISCLAIMER = (
    "This recommendation is generated by an AI model and is for informational purposes only. "
    "It does not constitute financial advice. Please consult a qualified financial advisor "
    "before making investment decisions."
)

router = APIRouter()


class PortfolioHoldingInput(BaseModel):
    model_config = ConfigDict(frozen=True)

    symbol: str
    name: str
    asset_class: str
    shares: float
    current_value: float
    currency: str


class PortfolioInput(BaseModel):
    model_config = ConfigDict(frozen=True)

    holdings: list[PortfolioHoldingInput]
    cash_balance: float
    total_value: float
    currency: str
    risk_tolerance: str | None = None


class LLMRecommendation(BaseModel):
    recommendation: str
    rationale: str


class RecommendationResponse(BaseModel):
    model_config = ConfigDict(frozen=True)

    recommendation: str
    rationale: str
    disclaimer: str


def _build_prompt(portfolio: PortfolioInput) -> str:
    lines = [
        f"Total portfolio value: {portfolio.total_value} {portfolio.currency}",
        f"Cash balance: {portfolio.cash_balance} {portfolio.currency}",
    ]
    if portfolio.risk_tolerance:
        lines.append(f"Investor risk tolerance: {portfolio.risk_tolerance}")
    lines.append("Holdings:")
    for h in portfolio.holdings:
        lines.append(
            f"  - {h.name} ({h.symbol}): {h.shares} shares worth {h.current_value} {h.currency} [{h.asset_class}]"
        )
    return "\n".join(lines)


@router.post(
    "/advisor/recommendation",
    response_model=RecommendationResponse,
    responses={
        502: {"description": "AI service request failed or returned an unparsable response"},
        503: {"description": "AI service is not configured"},
    },
)
async def generate_recommendation(
    portfolio: PortfolioInput,
    settings: Annotated[Settings, Depends(get_settings)],
) -> RecommendationResponse:
    if not settings.logos_api_key:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service is not configured",
        )

    client = make_logos_client(settings)
    try:
        response = await client.chat.completions.create(
            model=LOGOS_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a financial advisor assistant. Analyze the user's investment portfolio "
                        "and respond with a JSON object containing exactly two string fields: "
                        '"recommendation" (1-2 sentences of actionable advice) and '
                        '"rationale" (2-3 sentences explaining the reasoning). '
                        "Tailor your advice to the investor's stated risk tolerance when provided. "
                        "Be professional and data-driven."
                    ),
                },
                {"role": "user", "content": _build_prompt(portfolio)},
            ],
            response_format={"type": "json_object"},
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service request failed",
        ) from exc

    choices = response.choices or []
    content = choices[0].message.content if choices else None
    if not content:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service returned an empty response",
        )

    try:
        llm = LLMRecommendation.model_validate(json.loads(content))
    except (json.JSONDecodeError, ValidationError) as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI service returned an unparsable response",
        ) from exc

    return RecommendationResponse(
        recommendation=llm.recommendation,
        rationale=llm.rationale,
        disclaimer=DISCLAIMER,
    )
