// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type LivenessAiHealthLivenessGetData = {
  body?: never
  path?: never
  query?: never
  url: "/ai/health/liveness"
}

export type LivenessAiHealthLivenessGetResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type LivenessAiHealthLivenessGetResponse =
  LivenessAiHealthLivenessGetResponses[keyof LivenessAiHealthLivenessGetResponses]

export type ReadinessAiHealthReadinessGetData = {
  body?: never
  path?: never
  query?: never
  url: "/ai/health/readiness"
}

export type ReadinessAiHealthReadinessGetResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type ReadinessAiHealthReadinessGetResponse =
  ReadinessAiHealthReadinessGetResponses[keyof ReadinessAiHealthReadinessGetResponses]
