// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * PortfolioHoldingInput
 */
export type PortfolioHoldingInput = {
  /**
   * Symbol
   */
  symbol: string
  /**
   * Name
   */
  name: string
  /**
   * Asset Class
   */
  asset_class: string
  /**
   * Shares
   */
  shares: number
  /**
   * Current Value
   */
  current_value: number
  /**
   * Currency
   */
  currency: string
}

/**
 * PortfolioInput
 */
export type PortfolioInput = {
  /**
   * Holdings
   */
  holdings: Array<PortfolioHoldingInput>
  /**
   * Cash Balance
   */
  cash_balance: number
  /**
   * Total Value
   */
  total_value: number
  /**
   * Currency
   */
  currency: string
  /**
   * Risk Tolerance
   */
  risk_tolerance?: "CONSERVATIVE" | "MODERATE" | "AGGRESSIVE" | null
}

/**
 * RecommendationResponse
 */
export type RecommendationResponse = {
  /**
   * Recommendation
   */
  recommendation: string
  /**
   * Rationale
   */
  rationale: string
  /**
   * Disclaimer
   */
  disclaimer: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type LivenessAiHealthLivenessGetData = {
  body?: never
  path?: never
  query?: never
  url: "/ai/health/liveness"
}

export type LivenessAiHealthLivenessGetResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type LivenessAiHealthLivenessGetResponse =
  LivenessAiHealthLivenessGetResponses[keyof LivenessAiHealthLivenessGetResponses]

export type ReadinessAiHealthReadinessGetData = {
  body?: never
  path?: never
  query?: never
  url: "/ai/health/readiness"
}

export type ReadinessAiHealthReadinessGetResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type ReadinessAiHealthReadinessGetResponse =
  ReadinessAiHealthReadinessGetResponses[keyof ReadinessAiHealthReadinessGetResponses]

export type LatestRecommendationAiAdvisorRecommendationGetData = {
  body?: never
  path?: never
  query?: never
  url: "/ai/advisor/recommendation"
}

export type LatestRecommendationAiAdvisorRecommendationGetErrors = {
  /**
   * No recommendation has been generated yet
   */
  404: unknown
}

export type LatestRecommendationAiAdvisorRecommendationGetResponses = {
  /**
   * Successful Response
   */
  200: RecommendationResponse
}

export type LatestRecommendationAiAdvisorRecommendationGetResponse =
  LatestRecommendationAiAdvisorRecommendationGetResponses[keyof LatestRecommendationAiAdvisorRecommendationGetResponses]

export type GenerateRecommendationAiAdvisorRecommendationPostData = {
  body: PortfolioInput
  path?: never
  query?: never
  url: "/ai/advisor/recommendation"
}

export type GenerateRecommendationAiAdvisorRecommendationPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
  /**
   * AI service request failed or returned an unparsable response
   */
  502: unknown
  /**
   * AI service is not configured
   */
  503: unknown
}

export type GenerateRecommendationAiAdvisorRecommendationPostError =
  GenerateRecommendationAiAdvisorRecommendationPostErrors[keyof GenerateRecommendationAiAdvisorRecommendationPostErrors]

export type GenerateRecommendationAiAdvisorRecommendationPostResponses = {
  /**
   * Successful Response
   */
  200: RecommendationResponse
}

export type GenerateRecommendationAiAdvisorRecommendationPostResponse =
  GenerateRecommendationAiAdvisorRecommendationPostResponses[keyof GenerateRecommendationAiAdvisorRecommendationPostResponses]
