// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

/**
 * Successful Response
 */
export const livenessAiHealthLivenessGetResponseSchema = z.string()

/**
 * Successful Response
 */
export const readinessAiHealthReadinessGetResponseSchema = z.string()
